INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (-1, '[Unknown]', '0033B2', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (0, 'Black', '05131D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1, 'Blue', '0055BF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (2, 'Green', '237841', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (3, 'Dark Turquoise', '008F9B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (4, 'Red', 'C91A09', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (5, 'Dark Pink', 'C870A0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (6, 'Brown', '583927', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (7, 'Light Gray', '9BA19D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (8, 'Dark Gray', '6D6E5C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (9, 'Light Blue', 'B4D2E3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (10, 'Bright Green', '4B9F4A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (11, 'Light Turquoise', '55A5AF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (12, 'Salmon', 'F2705E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (13, 'Pink', 'FC97AC', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (14, 'Yellow', 'F2CD37', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (15, 'White', 'FFFFFF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (17, 'Light Green', 'C2DAB8', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (18, 'Light Yellow', 'FBE696', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (19, 'Tan', 'E4CD9E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (20, 'Light Violet', 'C9CAE2', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (21, 'Glow In Dark Opaque', 'D4D5C9', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (22, 'Purple', '81007B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (23, 'Dark Blue-Violet', '2032B0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (25, 'Orange', 'FE8A18', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (26, 'Magenta', '923978', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (27, 'Lime', 'BBE90B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (28, 'Dark Tan', '958A73', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (29, 'Bright Pink', 'E4ADC8', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (30, 'Medium Lavender', 'AC78BA', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (31, 'Lavender', 'E1D5ED', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (32, 'Trans-Black IR Lens', '635F52', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (33, 'Trans-Dark Blue', '0020A0', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (34, 'Trans-Green', '84B68D', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (35, 'Trans-Bright Green', 'D9E4A7', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (36, 'Trans-Red', 'C91A09', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (40, 'Trans-Brown', '635F52', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (41, 'Trans-Light Blue', 'AEEFEC', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (42, 'Trans-Neon Green', 'F8F184', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (43, 'Trans-Very Lt Blue', 'C1DFF0', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (45, 'Trans-Dark Pink', 'DF6695', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (46, 'Trans-Yellow', 'F5CD2F', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (47, 'Trans-Clear', 'FCFCFC', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (52, 'Trans-Purple', 'A5A5CB', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (54, 'Trans-Neon Yellow', 'DAB000', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (57, 'Trans-Neon Orange', 'FF800D', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (60, 'Chrome Antique Brass', '645A4C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (61, 'Chrome Blue', '6C96BF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (62, 'Chrome Green', '3CB371', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (63, 'Chrome Pink', 'AA4D8E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (64, 'Chrome Black', '1B2A34', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (68, 'Very Light Orange', 'F3CF9B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (69, 'Light Purple', 'CD6298', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (70, 'Reddish Brown', '582A12', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (71, 'Light Bluish Gray', 'A0A5A9', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (72, 'Dark Bluish Gray', '6C6E68', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (73, 'Medium Blue', '5A93DB', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (74, 'Medium Green', '73DCA1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (75, 'Speckle Black-Copper', '05131D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (76, 'Speckle DBGray-Silver', '6C6E68', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (77, 'Light Pink', 'FECCCF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (78, 'Light Nougat', 'F6D7B3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (79, 'Milky White', 'FFFFFF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (80, 'Metallic Silver', 'A5A9B4', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (81, 'Metallic Green', '899B5F', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (82, 'Metallic Gold', 'DBAC34', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (84, 'Medium Nougat', 'AA7D55', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (85, 'Dark Purple', '3F3691', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (86, 'Light Brown', '7C503A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (89, 'Royal Blue', '4C61DB', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (92, 'Nougat', 'D09168', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (100, 'Light Salmon', 'FEBABD', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (110, 'Violet', '4354A3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (112, 'Medium Bluish Violet', '6874CA', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (114, 'Glitter Trans-Dark Pink', 'DF6695', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (115, 'Medium Lime', 'C7D23C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (117, 'Glitter Trans-Clear', 'FFFFFF', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (118, 'Aqua', 'B3D7D1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (120, 'Light Lime', 'D9E4A7', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (125, 'Light Orange', 'F9BA61', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (129, 'Glitter Trans-Purple', 'A5A5CB', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (132, 'Speckle Black-Silver', '05131D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (133, 'Speckle Black-Gold', '05131D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (134, 'Copper', 'AE7A59', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (135, 'Pearl Light Gray', '9CA3A8', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (137, 'Pearl Sand Blue', '7988A1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (142, 'Pearl Light Gold', 'DCBC81', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (143, 'Trans-Medium Blue', 'CFE2F7', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (148, 'Pearl Dark Gray', '575857', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (150, 'Pearl Very Light Gray', 'ABADAC', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (151, 'Very Light Bluish Gray', 'E6E3E0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (158, 'Yellowish Green', 'DFEEA5', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (178, 'Flat Dark Gold', 'B48455', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (179, 'Flat Silver', '898788', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (182, 'Trans-Orange', 'F08F1C', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (183, 'Pearl White', 'F2F3F2', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (191, 'Bright Light Orange', 'F8BB3D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (212, 'Bright Light Blue', '9FC3E9', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (216, 'Rust', 'B31004', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (226, 'Bright Light Yellow', 'FFF03A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (230, 'Trans-Pink', 'E4ADC8', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (232, 'Sky Blue', '7DBFDD', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (236, 'Trans-Light Purple', '96709F', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (272, 'Dark Blue', '0A3463', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (288, 'Dark Green', '184632', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (294, 'Glow In Dark Trans', 'BDC6AD', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (297, 'Pearl Gold', 'AA7F2E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (308, 'Dark Brown', '352100', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (313, 'Maersk Blue', '3592C3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (320, 'Dark Red', '720E0F', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (321, 'Dark Azure', '078BC9', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (322, 'Medium Azure', '36AEBF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (323, 'Light Aqua', 'ADC3C0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (326, 'Olive Green', '9B9A5A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (334, 'Chrome Gold', 'BBA53D', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (335, 'Sand Red', 'D67572', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (351, 'Medium Dark Pink', 'F785B1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (366, 'Earth Orange', 'FA9C1C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (373, 'Sand Purple', '845E84', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (378, 'Sand Green', 'A0BCAC', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (379, 'Sand Blue', '6074A1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (383, 'Chrome Silver', 'E0E0E0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (450, 'Fabuland Brown', 'B67B50', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (462, 'Medium Orange', 'FFA70B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (484, 'Dark Orange', 'A95500', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (503, 'Very Light Gray', 'E6E3DA', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1000, 'Glow in Dark White', 'D9D9D9', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1001, 'Medium Violet', '9391E4', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1002, 'Glitter Trans-Neon Green', 'C0F500', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1003, 'Glitter Trans-Light Blue', '68BCC5', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1004, 'Trans-Flame Yellowish Orange', 'FCB76D', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1005, 'Trans-Fire Yellow', 'FBE890', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1006, 'Trans-Light Royal Blue', 'B4D4F7', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1007, 'Reddish Lilac', '8E5597', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1008, 'Vintage Blue', '039CBD', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1009, 'Vintage Green', '1E601E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1010, 'Vintage Red', 'CA1F08', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1011, 'Vintage Yellow', 'F3C305', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1012, 'Fabuland Orange', 'EF9121', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1013, 'Modulex White', 'F4F4F4', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1014, 'Modulex Light Bluish Gray', 'AfB5C7', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1015, 'Modulex Light Gray', '9C9C9C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1016, 'Modulex Charcoal Gray', '595D60', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1017, 'Modulex Tile Gray', '6B5A5A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1018, 'Modulex Black', '4D4C52', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1019, 'Modulex Tile Brown', '330000', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1020, 'Modulex Terracotta', '5C5030', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1021, 'Modulex Brown', '907450', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1022, 'Modulex Buff', 'DEC69C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1023, 'Modulex Red', 'B52C20', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1024, 'Modulex Pink Red', 'F45C40', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1025, 'Modulex Orange', 'F47B30', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1026, 'Modulex Light Orange', 'F7AD63', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1027, 'Modulex Light Yellow', 'FFE371', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1028, 'Modulex Ochre Yellow', 'FED557', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1029, 'Modulex Lemon', 'BDC618', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1030, 'Modulex Pastel Green', '7DB538', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1031, 'Modulex Olive Green', '7C9051', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1032, 'Modulex Aqua Green', '27867E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1033, 'Modulex Teal Blue', '467083', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1034, 'Modulex Tile Blue', '0057A6', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1035, 'Modulex Medium Blue', '61AFFF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1036, 'Modulex Pastel Blue', '68AECE', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1037, 'Modulex Violet', 'BD7D85', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1038, 'Modulex Pink', 'F785B1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1039, 'Modulex Clear', 'FFFFFF', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1040, 'Modulex Foil Dark Gray', '595D60', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1041, 'Modulex Foil Light Gray', '9C9C9C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1042, 'Modulex Foil Dark Green', '006400', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1043, 'Modulex Foil Light Green', '7DB538', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1044, 'Modulex Foil Dark Blue', '0057A6', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1045, 'Modulex Foil Light Blue', '68AECE', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1046, 'Modulex Foil Violet', '4B0082', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1047, 'Modulex Foil Red', '8B0000', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1048, 'Modulex Foil Yellow', 'FED557', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1049, 'Modulex Foil Orange', 'F7AD63', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1050, 'Coral', 'FF698F', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1051, 'Pastel Blue', '5AC4DA', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1052, 'Glitter Trans-Orange', 'F08F1C', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1053, 'Trans-Blue Opal', '68BCC5', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1054, 'Trans-Dark Pink Opal', 'CE1D9B', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1055, 'Trans-Clear Opal', 'FCFCFC', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1056, 'Trans-Brown Opal', '583927', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1057, 'Trans-Light Bright Green', 'C9E788', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1058, 'Trans-Light Green', '94E5AB', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1059, 'Trans-Purple Opal', '8320B7', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1060, 'Trans-Green Opal', '84B68D', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1061, 'Trans-Dark Blue Opal', '0020A0', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1062, 'Vibrant Yellow', 'EBD800', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1063, 'Pearl Copper', 'B46A00', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1064, 'Fabuland Red', 'FF8014', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1065, 'Reddish Gold', 'AC8247', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1066, 'Curry', 'DD982E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1067, 'Dark Nougat', 'AD6140', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1068, 'Bright Reddish Orange', 'EE5434', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1069, 'Pearl Red', 'D60026', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1070, 'Pearl Blue', '0059A3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1071, 'Pearl Green', '008E3C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1072, 'Pearl Brown', '57392C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1073, 'Pearl Black', '0A1327', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1074, 'Duplo Blue', '009ECE', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1075, 'Duplo Medium Blue', '3E95B6', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1076, 'Duplo Lime', 'FFF230', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1077, 'Fabuland Lime', '78FC78', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1078, 'Duplo Medium Green', '468A5F', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1079, 'Duplo Light Green', '60BA76', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1080, 'Light Tan', 'F3C988', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1081, 'Rust Orange', '872B17', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1082, 'Clikits Pink', 'FE78B0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1083, 'Two-tone Copper', '945148', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1084, 'Two-tone Gold', 'AB673A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1085, 'Two-tone Silver', '737271', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1086, 'Pearl Lime', '6A7944', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1087, 'Duplo Pink', 'FF879C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1088, 'Medium Brown', '755945', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1089, 'Warm Tan', 'CCA373', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1090, 'Duplo Turquoise', '3FB69E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1091, 'Warm Yellowish Orange', 'FFCB78', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1092, 'Metallic Copper', '764D3B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1093, 'Light Lilac', '9195CA', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1094, 'Trans-Medium Purple', '8D73B3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1095, 'Trans-Black', '635F52', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1096, 'Glitter Trans-Bright Green', 'D9E4A7', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1097, 'Glitter Trans-Medium Purple', '8D73B3', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1098, 'Glitter Trans-Green', '84B68D', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1099, 'Glitter Trans-Pink', 'E4ADC8', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1100, 'Clikits Yellow', 'FFCF0B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1101, 'Duplo Dark Purple', '5F27AA', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1102, 'Trans-Neon Red', 'FF0040', 't');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1103, 'Pearl Titanium', '3E3C39', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1104, 'HO Aqua', 'B3D7D1', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1105, 'HO Azure', '1591cb', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1106, 'HO Blue-gray', '354e5a', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1107, 'HO Cyan', '5b98b3', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1108, 'HO Dark Aqua', 'a7dccf', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1109, 'HO Dark Blue', '0A3463', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1110, 'HO Dark Gray', '6D6E5C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1111, 'HO Dark Green', '184632', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1112, 'HO Dark Lime', 'b2b955', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1113, 'HO Dark Red', '631314', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1114, 'HO Dark Sand Green', '627a62', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1115, 'HO Dark Turquoise', '10929d', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1116, 'HO Earth Orange', 'bb771b', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1117, 'HO Gold', 'b4a774', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1118, 'HO Light Aqua', 'a3d1c0', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1119, 'HO Light Brown', '965336', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1120, 'HO Light Gold', 'cdc298', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1121, 'HO Light Tan', 'f9f1c7', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1122, 'HO Light Yellow', 'f5fab7', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1123, 'HO Medium Blue', '7396c8', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1124, 'HO Medium Red', 'c01111', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1125, 'HO Metallic Blue', '0d4763', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1126, 'HO Metallic Dark Gray', '5e5e5e', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1127, 'HO Metallic Green', '879867', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1128, 'HO Metallic Sand Blue', '5f7d8c', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1129, 'HO Olive Green', '9B9A5A', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1130, 'HO Rose', 'd06262', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1131, 'HO Sand Blue', '6e8aa6', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1132, 'HO Sand Green', 'A0BCAC', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1133, 'HO Tan', 'E4CD9E', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1134, 'HO Titanium', '616161', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1135, 'Metal', 'A5ADB4', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1136, 'Reddish Orange', 'CA4C0B', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1137, 'Sienna Brown', '915C3C', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (1138, 'Umber Brown', '5E3F33', 'f');
INSERT INTO COLORS (id, name, rgb, is_trans) VALUES (9999, '[No Color/Any Color]', '05131D', 'f');
